const mockInitialState = {
  user: {
    email: 'josiel.jcc@hotmail.com',
  },
  wallet: {
    currencies: [
      'USD',
      'CAD',
      'GBP',
      'ARS',
      'BTC',
      'LTC',
      'EUR',
      'JPY',
      'CHF',
      'AUD',
      'CNY',
      'ILS',
      'ETH',
      'XRP',
      'DOGE',
    ],
    expenses: [
      // {
      //   id: '',
      //   value: '',
      //   currency: '',
      //   method: '',
      //   tag: '',
      //   description: '',
      //   exchangeRates: '',
      // },
      {
        id: 0,
        value: '200',
        description: 'supermercado',
        currency: 'USD',
        method: 'Dinheiro',
        tag: 'Alimentação',
        exchangeRates: {
          USD: {
            code: 'USD',
            codein: 'BRL',
            name: 'Dólar Americano/Real Brasileiro',
            high: '5.1801',
            low: '5.1796',
            varBid: '0.001',
            pctChange: '0.02',
            bid: '5.1796',
            ask: '5.1806',
            timestamp: '1667268035',
            create_date: '2022-10-31 23:00:35',
          },
        },
      },
      {
        id: 1,
        value: '58',
        description: 'fone de ouvido',
        currency: 'CAD',
        method: 'Dinheiro',
        tag: 'Lazer',
        exchangeRates: {
          CAD: {
            code: 'CAD',
            codein: 'BRL',
            name: 'Dólar Canadense/Real Brasileiro',
            high: '3.811',
            low: '3.8003',
            varBid: '0.0099',
            pctChange: '0.26',
            bid: '3.8099',
            ask: '3.8118',
            timestamp: '1667269531',
            create_date: '2022-10-31 23:25:31',
          },
        },
      },
    ],
    editor: false,
    idToEdit: 0,
    isFetching: false,
  },
};

export default mockInitialState;
